### PR TITLE
backend: refactor client list handling, context handling, and a few other things

### PR DESCRIPTION
**Pull request by DeedleFake**
[The `context` packages documentation](https://pkg.go.dev/context) says

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

This refactors `Server` to remove the `context.Context` and pass it explicitly. In so doing, it also fixes a number of bugs where incorrect contexts were used for some things, potentially resulting in operations continuing in the background after they were no longer needed.

It also removes the separate loops for different client events and puts them all in one big `for-select` loop. This allows the removal of `sync.Map` from [a usage that it is not optimized for](https://pkg.go.dev/sync#Map), the removal of the need for locks around map access despite it already being a `sync.Map`, the ability to get the length of the map in `O(1)` with just a simple `len(clients)`, and the ability to close the server by canceling the context.

Unfortunately, I couldn't really test these changes very well as I was unsure how to get the frontend to work locally. I found `const production = true` and set it to `false`, but it just kept getting 403s trying to load some third-party script. The changes are pretty straightforward, though, so I'd be surprised if it breaks. I _was_ able to test the changes to the initialization and shutdown logic, though, and those all seemed to work as intended.

I'd like to send a follow-up that removes the custom rate-limiting logic and replaces it with usage of the [`golang.org/x/time/rate`](https://pkg.go.dev/golang.org/x/time/rate) package, but I thought it would be best not to put too much in a single pull request.

### CODE REVIEW

**Comment by joshuarichards001** [comment]
This is awesome! Thanks so much for taking a look at my implementation. The best practice side of things is still unknown to me with Go. I'm at work right now but I'll take a look at the changes locally on my machine later.

**Comment by DeedleFake** [comment]
Sounds good.

On the topic of best practices, the repository's layout is somewhat unusual. The most common setup is to put the `go.mod` in the root of the repo and then name the module based on the repo's path, i.e. `github.com/joshuarichards001/pixels`. That module name + a path to a directory in the repo then becomes the import path for packages in the module, i.e. `github.com/joshuarichards001/pixels/internal/set` or something. The module will then also get its version from (mostly) semver-compatible `vX.X.X` git tags. It's possible to do it in a subdirectory, as is having multiple modules in a repo, but tagging them needs to be done as `path/to/directory/vX.X.X` instead, which is a bit weird.

Also, very minor nitpick but filenames are usually entirely lowercase with their words run together, so `rateLimit.go` would be `ratelimit.go` instead. Underscores are used for indicating things to the build system, so they're not really an option for separating words, unfortunately.

**Comment by joshuarichards001** [comment]
Interesting, I'll take a look at adding those changes too. Thanks for bringing that rate limiting package to my attention too! I don't know how I didn't find that haha.

As for running the frontend locally. Sorry that it wasn't really something I thought about when sharing the code haha. Your problem might be the HCaptcha. [Here's](https://docs.hcaptcha.com/#local-development) some details on getting it running locally that could help? 

Also I have the environment variables HCAPTCHA_SECRET, REDIS_ADDRESS, and REDIS_PASSWORD in the Go app. You could set up an hCaptcha account or try the local dev approach. For Redis, feel free to do that locally or on the Redis hosted solution (which is what I did) for local dev if you'd like.

Let me know if that helps! I'll try and get some instructions for local dev this weekend.

**Comment by DeedleFake** [comment]
I'll take a look at that and see if I can figure out how to get it working. I already have a local Redis so that shouldn't be a problem, I think. Thanks.

**Comment by DeedleFake** [comment]
ee1adaa8aa2b6332b29a18d1d379d04320374801 mentions that there was a lot of crashing before adding the mutex. My guess is that you ran into this section from the docs for `websocket`:

```
# Concurrency

Connections support one concurrent reader and one concurrent writer.

Applications are responsible for ensuring that no more than one goroutine
calls the write methods (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON,
EnableWriteCompression, SetCompressionLevel) concurrently and that no more than
one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage,
ReadJSON, SetPongHandler, SetPingHandler) concurrently.

The Close and WriteControl methods can be called concurrently with all other
methods.
```

Your current setup has a single thread that's reading and two threads that can write to each client. I've removed the global lock that blocks _all_ writes on all others and replaced it with individual locks per client connection instead. When you're testing, especially if you think that there's a potential concurrency problem, you should use the `-race` build flag to activate the race detector. It's off by default because it adds a _massive_ amount of overhead, but if there's a race condition, it'll find it.

**Comment by DeedleFake** [comment]
Hmmm... I took a look at the hCaptcha documentation that you linked, and it says that opening a local file won't work. The Go server hasn't been set up to serve files, though. How are you loading the frontend into the browser locally?

**Comment by joshuarichards001** [comment]
Dam I wish you were around while I was getting 100 pixels per second and 100 concurrent websocket connections!! As you can see from my code quality, that period was a bit of a mess haha. Thanks so much!

Do you have any resources that I should go through to get a better fundamental understanding of Go?

As for hCaptcha, I'm loading the frontend using the "[Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)" extension in VSCode. If you try and create a free hCaptcha account and just set it up that was does it work? Otherwise you can probably just hack the websocket to not require hCaptcha pretty easily.

**Comment by DeedleFake** [comment]
> Do you have any resources that I should go through to get a better fundamental understanding of Go?

What languages do you have experience with? I'm guessing JavaScript primarily?

> As for hCaptcha, I'm loading the frontend using the "[Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)" extension in VSCode. If you try and create a free hCaptcha account and just set it up that was does it work? Otherwise you can probably just hack the websocket to not require hCaptcha pretty easily.

Ah, I'm not using VSCode. Hmmm... You seem to be deploying the backend to Fly.io. Is the frontend deployed somewhere else? Would it be feasible to serve the frontend _from_ the backend, or are you putting all the static files in a CDN or something? Does it have something to do with Vercel? I see Vercel's name thrown around a lot but I'm not actually sure what they do. I know it's JavaScript-related, though.

If your entire frontend is static, it's pretty easy to serve from a Go backend. You can even embed it so that you just have a single binary for the entire frontend and backend. Looks something like

```go
import (
  "embed"
  "io/fs"
  "net/http"
)

//go:embed frontend
var frontend embed.FS

func main() {
  http.Handle("GET /", http.FileServerFS(fs.Sub(frontend, "frontend")))
  panic(http.ListenAndServe(":8080", nil))
}
```

Not saying that it makes sense for this particular project, but it is an option for simple things.

**Comment by DeedleFake** [comment]
Actually, on that topic, I can simplify your Dockerfile a bit, too, but I'm not sure how much in there is specific to your deployment. For example, do you need the container to have a full Debian userspace in it or would it be O.K. to switch it to a smaller one? Go binaries can be compiled statically with no C dependencies at all, which can allow them to be deployed into a `FROM scratch` container or, as I discovered recently, a Distroless `static` container as it is essentially `scratch` but with a few things like the root certificates included for you.

Also, you don't need to run `go mod download` manually in the Dockerfile. Building will automatically download any required dependencies that aren't already there.

Here's what I rewrote the Dockerfile as:

```dockerfile
ARG GO_VERSION=1
FROM golang:${GO_VERSION}-alpine AS builder

ENV CGO_ENABLED=0
WORKDIR /build
COPY go.mod .
COPY go.sum .
COPY *.go .
RUN go build -v -o pixels

FROM gcr.io/distroless/static

COPY --from=builder /build/pixels /pixels

EXPOSE 8080
CMD ["/pixels"]
```

**Review by joshuarichards001 — APPROVED** [review]
Hey mate, sorry I was super sick over the weekend so I'm just getting to this now. Everything looks great! This cleans up the code a lot, I really appreciate it!

If you'd like, feel free to make any more PR's you see fit and I'll take a look at them and get them deployed :)

**Pull request merged**
